### ISSUE TITLE
Thanks and "help!"

### ISSUE THREAD

**Issue by gingerbeardman** [frozenpandaman/kaiba#1]
These are the first .ass I've ever seen.

I'm eager to use them, but I don't know how.

I've put them alongside my episodes, and they show up but without the custom fonts. The fonts folder is there in the same folder as the .ass files and my video files.

Is there a guide anywhere showing how I should install this pack? And recommended players?

Thanks for all your effort on this!

**Comment by gingerbeardman** [comment]
Ah! 

I just tried the IINA player on macOS and my setup works just fine. Hurrah!

So I guess support playing back through Plex is limited.

My problem, I'll make sure to watch it the best way.

Thanks again!

**Comment by frozenpandaman** [comment]
@gingerbeardman Glad you figured it out, and thank you for the kind words! I was going to recommend either [IINA](https://iina.io/) or [mpv](https://mpv.io/) for macOS. :) For future reference: dragging them onto the video open in your player should work (with the recommended fonts installed on your system too). Having the .ass file in the same folder as the video file with the same filename should make them load automatically as well.

I'm not too familiar with Plex but most web-based players don't support subtitles (softsubs aka "closed captions") – much less ones with fancy typesetting and not just plain text – and instead need the text burned permanently into the video itself (hardsubs aka "open captions"). You can do this with a program like Handbrake but it uses up a good amount of processing power. I'd recommend just playing it locally with a video player application if that's possible. :)

Finally, I'm hoping to release a v2 of these subtitles that are improved & cleaned up a lot later this year!
